apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: other
---

kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
spec:
  selector:
    app: jenkins
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: other
    protocol: TCP
    port: 50000
    targetPort: 50000
